### Необходимые библиотеки

In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Метод подбора
y = 0.4*x + 3 + noise

In [2]:
from ipywidgets import interactive
a = np.linspace(-5,5,50)
delta = np.random.uniform(-5,5, size=(50,))
d = .4 * a +3 + delta

def f(m, b):
    plt.figure(2)
    x = np.linspace(-10, 10, num=1000)
    plt.scatter(a,d)
    plt.plot(x, m * x + b, color='red')
    plt.ylim(-3, 5)
    plt.show()

interactive_plot = interactive(f, m=(-2.0, 2.0), b=(-3, 3, 0.5))
output = interactive_plot.children[-1]
output.layout.height = '400px'
interactive_plot

interactive(children=(FloatSlider(value=0.0, description='m', max=2.0, min=-2.0), FloatSlider(value=0.0, descr…

In [ ]:
### 0.6*x + 1.5

In [3]:
0.4 * 7.5 + 3 + np.random.rand()

6.370531060601381

In [4]:
0.6 * 7.5 + 1.5

6.0

### Функция создания таргета: <i><font color='red'>y = x_1 * 2 + x_2 + random_noise</font></i>

## Расчет beta коэффициентов с помощью матричной математики. Расчет потерь - метод наименьших квадратов

#### Dataset

In [5]:
X_1 = np.linspace(1,30,150)
X_2 = X_1 + 11.5
Y = 2 * X_1 + 0.5 * X_2 + np.random.rand()
df = pd.DataFrame({"X_1":X_1,'X_2':X_2,"Y":Y})

In [7]:
df

,X_1,X_2,Y
0,1.000000,12.500000,8.679595
1,1.194631,12.694631,9.166172
2,1.389262,12.889262,9.652749
3,1.583893,13.083893,10.139326
4,1.778523,13.278523,10.625904
...,...,...,...
145,29.221477,40.721477,79.233286
146,29.416107,40.916107,79.719863
147,29.610738,41.110738,80.206441
148,29.805369,41.305369,80.693018


#### Beta coeffs: <i><font color='red'> np.dot((np.linalg.inv(np.dot(X.T,X))), np.dot(X.T,Y)) </font></i>

In [8]:
X = df.drop('Y',axis=1)
Y = df['Y']

In [9]:
betas = np.dot((np.linalg.inv(np.dot(X.T,X))), np.dot(X.T,Y))

In [10]:
betas

array([1.96264392, 0.53735608])

In [11]:
2* 31 + 0.5 * 42.5 + np.random.rand()

83.70066937751143

In [12]:
betas[0] * 31 + betas[1]*42.5

83.67959492729118

In [13]:
a = np.array([[1,2],[2,4]])
b = np.array([[2,13],[5,7]])

In [15]:
np.linalg.inv(b)

array([[-0.1372549 ,  0.25490196],
       [ 0.09803922, -0.03921569]])

In [22]:
X_1 = np.linspace(1,30,150)
X_2 = X_1 + 11.5
Y = X_1 ** 3 + np.exp(np.sin(X_2)) + np.random.rand()
df = pd.DataFrame({"X_1":X_1,'X_2':X_2,"Y":Y})

In [23]:
df

,X_1,X_2,Y
0,1.000000,12.500000,2.702430
1,1.194631,12.694631,3.607959
2,1.389262,12.889262,4.821370
3,1.583893,13.083893,6.380189
4,1.778523,13.278523,8.314519
...,...,...,...
145,29.221477,40.721477,24953.956518
146,29.416107,40.916107,25455.668655
147,29.610738,41.110738,25964.103983
148,29.805369,41.305369,26479.304004


In [24]:
betas = np.dot((np.linalg.inv(np.dot(X.T,X))), np.dot(X.T,Y))

In [25]:
betas

array([1381.14364895, -532.56075595])

In [26]:
31 ** 3 + np.exp(np.sin(42.5)) + np.random.rand()

29791.452205633756

In [27]:
betas[0] * 31 + betas[1]*42.5

20181.620989567902