In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

### Загружаем данные


In [2]:
df = pd.read_csv('seattle-weather.csv')

### Основная информация о данных

In [3]:
df.head()

,date,precipitation,temp_max,temp_min,wind,weather
0,2012-01-01,0.0,12.8,5.0,4.7,drizzle
1,2012-01-02,10.9,10.6,2.8,4.5,rain
2,2012-01-03,0.8,11.7,7.2,2.3,rain
3,2012-01-04,20.3,12.2,5.6,4.7,rain
4,2012-01-05,1.3,8.9,2.8,6.1,rain


In [20]:
df['weather'].value_counts()

,count
weather,
rain,641
sun,640
fog,101
drizzle,53
snow,26


### Конвертация колонки с датой. Выделение признака

In [5]:
df['date'] = pd.to_datetime(df['date'])

In [7]:
df['month'] = df['date'].dt.month

In [8]:
df['quarter'] = df['date'].dt.quarter

### Создание колонки с таргетом. Приведение ее к нужному типу

In [19]:
df.loc[df['weather'] == 'fog', 'target'] = 1

In [17]:
df.head()

,date,precipitation,temp_max,temp_min,wind,weather,month,quarter,target
0,2012-01-01,0.0,12.8,5.0,4.7,drizzle,1,1,0.0
1,2012-01-02,10.9,10.6,2.8,4.5,rain,1,1,0.0
2,2012-01-03,0.8,11.7,7.2,2.3,rain,1,1,0.0
3,2012-01-04,20.3,12.2,5.6,4.7,rain,1,1,0.0
4,2012-01-05,1.3,8.9,2.8,6.1,rain,1,1,0.0


In [24]:
df['target'].value_counts()

,count
target,
1,741
0,720


In [23]:
df['target'] = df['target'].astype('int16')

### Удаление ненужных колонок и разделение датасета

In [27]:
df.head()

,precipitation,temp_max,temp_min,wind,month,quarter,target
0,0.0,12.8,5.0,4.7,1,1,0
1,10.9,10.6,2.8,4.5,1,1,0
2,0.8,11.7,7.2,2.3,1,1,0
3,20.3,12.2,5.6,4.7,1,1,0
4,1.3,8.9,2.8,6.1,1,1,0


In [26]:
df = df.drop(['weather','date'],axis=1)


### Логистическая регрессия : деление сета


In [28]:
X = df.drop(['target'],axis=1)
Y = df['target']

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

### Логистическая регрессия : Тренировка и прогноз

In [30]:
X_train,X_test, Y_train,Y_test = train_test_split(X,Y, test_size=.15)

In [31]:
model = LogisticRegression().fit(X_train, Y_train)

In [36]:
pipe = Pipeline(
    [
        ('Scaler',StandardScaler()),
        ('LR',LogisticRegression())
    ]
).fit(X_train, Y_train)

### Оценка работы модели

In [34]:
mean_absolute_error(Y_test, model.predict(X_test))

0.05

In [35]:
r2_score(Y_test, model.predict(X_test))

0.7999338624338623

In [39]:
pipe.score(X_test, Y_test)

0.9045454545454545

### Результаты

In [41]:
model.intercept_

array([-0.80188738])

In [42]:
Y_test.head(5)

,target
261,1
119,0
1012,1
1045,1
1013,0


In [44]:
predict = model.predict(X_test)

In [47]:
predict[0:5]

array([1, 0, 1, 1, 1], dtype=int16)

In [49]:
predict_pr = model.predict_proba(X_test)

In [50]:
predict_pr[0:5]

array([[5.68899007e-02, 9.43110099e-01],
       [1.00000000e+00, 6.22294142e-13],
       [2.13275633e-01, 7.86724367e-01],
       [8.53111591e-02, 9.14688841e-01],
       [4.89673561e-01, 5.10326439e-01]])

In [54]:
linear_[0:5]

array([  2.8080652 , -28.10536352,   1.30529257,   2.37227867,
         0.04131163])

In [51]:
model.classes_

array([0, 1], dtype=int16)

In [53]:
linear_ = model.decision_function(X_test)

In [55]:
def sigmoid(a):
  return 1 / (1 + np.exp(-a))

In [57]:
1 - sigmoid(-28.10536352)

0.9999999999993777