### Задание 1


Из списка выбрать индексы тех элементов, которые в сумме дают результат. Использовать одни и теже элементы дважды нельзя. Порядок вывода значения не имеет.

**_Пример 1_**

Входящий список: nums = [2,7,11,15], результат - 9

Выход: [0,1]

Объяснение: поскольку 2 + 7 = 9, а позиция элементов 0 и 1

**_Пример 2:_**

Входящий список: nums = [3,2,4], результат = 6

Выход: [1,2]

Объяснение: поскольку 2 + 4 = 6, а позиция элементов 1 и 2


In [99]:
from itertools import combinations
import numpy as np

nums = [1, 2, 7, 11, 15, 2, 3, 4, 3, 4, 9, 4]
result = 9


# Делаем из массива массив Numpy.
# Добавляем данные о индексе элемента и маску доступности элемента.
nums = np.array([nums, np.arange(0, len(nums), 1),
                np.full(len(nums), 1)]).transpose()
print("Initial array:\n", nums)
print("Result =", result)
# Флаг продолжения вычисления. Используется для остановки поиска комбинаций.
f_repeat = 1

# Проверяем, достаточно ли суммы элементов, чтобы получить результат
if (sum(nums[:, 0]) < result):
    f_repeat = 0
# Делаем недоступными элементы, которые больше результата
nums[nums[:, 0] > result, 2] = 0

while (f_repeat):
    f_repeat = 0
    # Формируем массив из оставшихся доступных элементов
    act_nums = nums[(nums[:, 2] == 1), :]
    # print(act_nums)
    # Итерируем по всем возможным сочетаниям, по возрастанию размера сочетания
    for act_len in (range(1, np.shape(act_nums)[0]+1)):
        # print(act_len)
        for comb_nums in combinations(act_nums, act_len):
            comb_nums = np.array(comb_nums)
            # Проверяем сумму элементов
            if (sum(comb_nums[:, 0]) == result):
                # Выводим результат
                print("Indices =", comb_nums[:, 1], sep=' ')
                # Делаем используемые элементы недоступными для дальнейшего использования
                nums[comb_nums[:, 1], 2] = 0
                # print(nums)
                # Выставляем флаг продолжения вычислений
                f_repeat = 1
                break
        if f_repeat:
            break

Initial array:
 [[ 1  0  1]
 [ 2  1  1]
 [ 7  2  1]
 [11  3  1]
 [15  4  1]
 [ 2  5  1]
 [ 3  6  1]
 [ 4  7  1]
 [ 3  8  1]
 [ 4  9  1]
 [ 9 10  1]
 [ 4 11  1]]
Result = 9
Indices = [10]
Indices = [1 2]
Indices = [0 7 9]
Indices = [ 5  6 11]


### Задание 2


В данной строке, включающей слова и пробелы, подсчитать количество символов в последнем слове. Слово - максимальная подстрока, внутри которой нет пробелов

**_Пример 1:_**

Входящая строка: s = "Hello World"

Выход: 5

Объяснение: Последнее слово "World" и его длина равна 5.

**_Пример 2:_**

Входящая строка: s = " fly me to the moon "

Выход: 4

Объяснение: Последнее слово "moon" и его длина равна 4.


In [100]:
inp_str = "   fly me  , to; :  the moonlight !!! "
# Заменяем символы, которые не будем учитывать в словах, на пробелы
whitespaced_str = inp_str.translate(inp_str.maketrans(",.:;!?", "      "))
# Разбиваем по пробелам на слова, берём длину первого с конца
len(whitespaced_str.split()[-1])

9

### Задание 3


Дано целое число INT. Напишите функцию, которая возвращает TRUE, если число ПАЛИНДРОМ(одинаково как сначала в конец, так и наоборот), и FALSE в противном случае.

**_Пример 1:_**

Вход: 121

Выход: TRUE

**_Пример 2:_**

Вход: 345

Выход: FALSE


In [101]:
# Отошёл от ТЗ по формату вывода, т.к. так удобнее проверять
test_nums = [121, 345, 1234321, 1234627]

for num in test_nums:
    print(num, end='\t')
    # Преобразуем число в строку, т.к. задача проще решается сравнением символьных строк, чем мат. преобразованиями
    num_str = str(num)
    # Определяем количество символов для сравнения
    half_len = len(num_str) // 2
    # Сравниваем первую половину и развёрнутую вторую половину строки
    if (num_str[:half_len] == num_str[-1:-half_len-1:-1]):
        print("TRUE")
    else:
        print("FALSE")

121	TRUE
345	FALSE
1234321	TRUE
1234627	FALSE
